jobs:
- template: .vsts-macOS-build.yml
  parameters:
    name: macOS
    pool:
      vmImage: 'macOS-10.13'

- template: .vsts-win-build.yml
  parameters:
    name: Windows
    pool:
      vmImage: 'vs2017-win2016'