parameters:
  pool: ''
  sign: false

jobs:
- job: Windows
  pool: ${{ parameters.pool }}

  steps:
  - checkout: self
    clean: true
    
  - task: GitVersion@3
    # Ignore gitversion for forks, until this is fixed:
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      updateAssemblyInfo: false

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.7.0
      checkLatest: false

  - task: MSBuild@1
    inputs:
      solution: Samples\XamlUIBasics\cs\AppUIBasics.sln
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: "/r /p:Configuration=Release /detailedsummary /m:16 /nr:false"
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(build.sourcesdirectory)/Samples/XamlUIBasics/cs/AppUIBasics.Wasm/bin/Release/netstandard2.0/dist
      Contents: '*.*'
      TargetFolder: $(build.artifactstagingdirectory)/XamlUIBasics-wasm
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: universal-samples-drop
      ArtifactType: Container
